---
tags: ["Err", "Result", "Ok", "unwrap"]
---

# 9.2 Result

: panic이 예상치 못한 상황에 발생한 에러라면,  
Result는 예상 가능한 문제에 대해 핸들링하기 위해 사용

```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```

> 성공시 Ok에 T 타입 value 반환  
> 실패시 Err에 E 타입 value 반환  
> Enum이긴 하나 `Result::Ok()`가 아닌 `Ok()`로 접근하면 된다 → prelude

<br/>

## Error 종류에 따른 패턴매칭

```rust
let greeting_file = match greeting_file_result {
    Ok(file) => file,
    Err(error) => match error.kind() {
        ErrorKind::NotFound => match File::create("hello.txt") {
            Ok(fc) => fc,
            Err(e) => panic!("Problem creating the file: {:?}", e),
        },
        other_error => {
            panic!("Problem opening the file: {:?}", other_error);
        }
    },
};
```

`io::Error`의 `.kind()` 이용, Error의 종류 알아내기  
→ 패턴매칭으로 처리

<br/>

## Result 패턴매칭 간소화

: prelude로 Result를 다루는 메소드 → 패턴매칭 간소화  

```rust
let greeting_file = File::open("hello.txt").unwrap_or_else(|error| {
    if error.kind() == ErrorKind::NotFound {
        File::create("hello.txt").unwrap_or_else(|error| {
            panic!("Problem creating the file: {:?}", error);
        })
    } else {
        panic!("Problem opening the file: {:?}", error);
    }
});
```

> `.unwrap_or_else()`  
> Ok<T> → T 반환  
> Err<E> → 클로저로 Err 핸들링

<br/>

### Ok → unwrap & Err → Panic

: `.unwrap()`  
: `.expect("ERR_MESSAGE")` 

<br/>

## Error propagate

: 에러 핸들링이 필요한 시점이 해당 코드에 국한되지 않을 수 있다.  
= 에러 핸들링을 다른 함수한테 맡기는 = 에러 핸들링을 calling function에 위임

→ 해당 로직 처리를 후처리로 미룬다는 점에서 `async`를 사용할 때와 비슷한 면이 있다

```rust
fn read_username_from_file() -> Result<String, io::Error> {
    let username_file_result = File::open("hello.txt");
    match username_file_result {
        Ok(file) => String::new("$file"),
        Err(e) => Err(e),
    };
}
```

> return으로 함수의 출력 관리

<br/>

### ? in Err propagate

: Result 값에 ? 연산을 이용하면, 해당 값이 `Result::Err`일 때 바로 return 때려버림

```rust
fn read_username_from_file() -> Result<String, io::Error> {
    let mut username_file = File::open("hello.txt")?;
}
```

…이후 많은 뒤의 얘기들은 생략…
